
image: Visual Studio 2019

clone_depth: 3

platform:
  - x64

configuration:
  - Release
  
matrix:
  fast_finish: false

build_script:
  - cmd: c:\"Program Files (x86)"\"Microsoft Visual Studio"\2019\Community\VC\Auxiliary\Build\vcvars64.bat
  - cmd: cl sqlite3.c -DSQLITE_API=__declspec(dllexport) -link -dll -out:sqlite3.dll

artifacts:
  - path: sqlite3.dll
    name: sqlite3.dll
  - path: sqlite3.lib
    name: sqlite3.lib
  - path: sqlite3.h
    name: sqlite3.h
